name: Build on DockerHub and Deploy on AWS
on:
  push:
    branches:
      - main
env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_TOKEN:  ${{ secrets.DOCKERHUB_TOKEN }}
  AWS_PRIVATE_KEY:  ${{ secrets.AWS_PRIVATE_KEY }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with: 
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push docker image
        uses: docker/build-push-action@v2
        with:
          context: ./
          push: true
          dockerfile: ./Dockerfile
          tags: vazidcovlant/dockerdemo:latest
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set permission for private key
        run: |
          echo "${{ secrets.AWS_PRIVATE_KEY }}" | tr -d '\r' > server-key.pem
          chmod 600 server-key.pem
      - name: Ensure Docker and Docker Compose are installed
        run: |
          ssh -o StrictHostKeyChecking=no -i server-key.pem ubuntu@ec2-18-233-157-140.compute-1.amazonaws.com << 'EOF'
            if ! command -v docker &> /dev/null
            then
              echo "Installing Docker..."
              sudo apt update
              sudo apt install -y docker.io
              sudo systemctl enable docker
              sudo systemctl start docker
              sudo usermod -aG docker ubuntu
            else
              echo "Docker is already installed."
            fi
            if ! docker compose version &> /dev/null
            then
              echo "Installing Docker Compose v2..."
              sudo apt update
              sudo apt install -y docker-compose-plugin
            else
              echo "Docker Compose v2 is already installed."
            fi
            docker compose version
          EOF
      - name: Clean up Docker system
        run: |
          ssh -o StrictHostKeyChecking=no -i server-key.pem ubuntu@ec2-18-233-157-140.compute-1.amazonaws.com << 'EOF'
            sudo docker system prune -af
          EOF
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Pull Docker Image
        run: |
          ssh -o StrictHostKeyChecking=no -i server-key.pem ubuntu@ec2-18-233-157-140.compute-1.amazonaws.com 'sudo docker pull vazidcovlant/dockerdemo:latest'
      - name: Stop and remove old container
        run: |
          ssh -o StrictHostKeyChecking=no -i server-key.pem ubuntu@ec2-18-233-157-140.compute-1.amazonaws.com << 'EOF'
            sudo docker stop dockerdemo || true
            sudo docker rm dockerdemo || true
          EOF
      - name: Run new container using Docker Compose
        run: |
          ssh -o StrictHostKeyChecking=no -i server-key.pem ubuntu@ec2-18-233-157-140.compute-1.amazonaws.com << 'EOF'
            echo "Checking available Docker images..."
            sudo docker images
            
            echo "Checking existing containers..."
            sudo docker ps -a
            
            echo "Stopping and removing old container..."
            sudo docker stop dockerdemo || true
            sudo docker rm dockerdemo || true

            echo "Running new container..."
            sudo docker compose up -d
            sleep 5

            echo "Verifying running containers..."
            sudo docker ps

            echo "Fetching container logs..."
            sudo docker logs dockerdemo || echo "No logs found."
          EOF
